### ISSUE TITLE
你的写的包不符合go mod规范

### ISSUE THREAD

**Issue by higker** [lihaotian0607/qrcode#1]
`../../../pkg/qr_code/qrcode.go:9:2: import "github.com/lihaotian0607/qrcode" is a program, not an importable package
`

你的包不能包含main.go这样别人导入不能使用,请你了解好golang mod 概念在写吧,谢谢,下午掉坑里了

**Comment by higker** [comment]
`package main`!!!!!!

**Comment by lihaotian0607** [comment]
之前是写个在本地跑的,后来打算发布一个可以导入的包 master分支里面已经是没问题的!
